App\Domain\Product\Product:
    type: entity

    table: shop_product
    id:
        id:
            type: uuid
    fields:
        createdAt:
            type: datetime_immutable

    embedded:
        name:
            class: App\Domain\Product\Properties\ProductName
            columnPrefix: false
        description:
            class: App\Domain\Product\Properties\ProductDescription
            columnPrefix: false
        price:
            class: App\Domain\Product\Properties\ProductPrice
            columnPrefix: false
